import type {
  AppSettings,
  AuditLog,
  CheckRun,
  DashboardMetrics,
  DomainWatch,
  NotificationEvent,
  RegistrationAttempt,
  SessionUser,
  Team,
} from "./types";

export const mockTeams: Team[] = [
  { id: "team-1", name: "Merkbescherming", slug: "brand-protection" },
  { id: "team-2", name: "Corporate IT", slug: "corporate-it" },
];

export const mockSessionUser: SessionUser = {
  id: "user-1",
  name: "Eva van Rijn",
  email: "eva@monitoring.internal",
  role: "ADMIN",
  teamId: "team-1",
  ntfyEnabled: true,
  lastLoginAt: "2026-03-29T16:48:00.000Z",
};

export const mockDomainWatches: DomainWatch[] = [
  {
    id: "dw-1",
    rootName: "northgrid",
    displayName: "northgrid primaire monitor",
    state: "active",
    frequency: "every_5_minutes",
    actionMode: "AUTO_REGISTER",
    priority: "high",
    tags: ["brand", "priority-1"],
    notes: "Escaleren naar legal wanneer .com of .io beschikbaar komt.",
    owner: {
      id: "user-1",
      name: "Eva van Rijn",
      email: "eva@monitoring.internal",
      role: "ADMIN",
      teamId: "team-1",
    },
    team: mockTeams[0],
    ntfyEnabled: true,
    ntfyTopic: "northgrid-domain-alerts",
    autoRegisterEnabled: true,
    registrarLinked: true,
    lastCheckAt: "2026-03-29T16:55:00.000Z",
    nextCheckAt: "2026-03-29T17:00:00.000Z",
    createdAt: "2026-03-20T08:10:00.000Z",
    updatedAt: "2026-03-29T16:55:00.000Z",
    extensions: [
      {
        id: "ext-1",
        tld: ".com",
        fqdn: "northgrid.com",
        status: "registered",
        lastCheckedAt: "2026-03-29T16:55:00.000Z",
        nextCheckAt: "2026-03-29T17:00:00.000Z",
        latencyMs: 184,
        rawSummary: "Registry-WHOIS geeft een actieve registratie aan tot 2027-01-19.",
        sourceProvider: "whois-generic",
        retryCount: 0,
        autoRegisterEnabled: true,
        notifyEnabled: true,
      },
      {
        id: "ext-2",
        tld: ".io",
        fqdn: "northgrid.io",
        status: "available",
        lastCheckedAt: "2026-03-29T16:55:00.000Z",
        nextCheckAt: "2026-03-29T17:00:00.000Z",
        latencyMs: 221,
        rawSummary: "Geen match voor northgrid.io teruggekregen van de provider.",
        sourceProvider: "whois-fallback",
        retryCount: 1,
        autoRegisterEnabled: true,
        notifyEnabled: true,
        registrationStatus: "pending",
      },
      {
        id: "ext-3",
        tld: ".nl",
        fqdn: "northgrid.nl",
        status: "registered",
        lastCheckedAt: "2026-03-29T16:55:00.000Z",
        nextCheckAt: "2026-03-29T17:00:00.000Z",
        latencyMs: 98,
        rawSummary: "SIDN-register toont nog steeds een actieve houder.",
        sourceProvider: "sidn-whois",
        retryCount: 0,
        autoRegisterEnabled: false,
        notifyEnabled: true,
      },
    ],
  },
  {
    id: "dw-2",
    rootName: "acmesecure",
    displayName: "acmesecure regionale scan",
    state: "attention",
    frequency: "hourly",
    actionMode: "NOTIFY",
    priority: "normal",
    tags: ["regional", "finance"],
    notes: "DACH focus. Geen auto-register zonder handmatige review.",
    owner: {
      id: "user-2",
      name: "Joris Meijer",
      email: "joris@monitoring.internal",
      role: "SECURITY_ANALYST",
      teamId: "team-1",
    },
    team: mockTeams[0],
    ntfyEnabled: true,
    autoRegisterEnabled: false,
    registrarLinked: false,
    lastCheckAt: "2026-03-29T15:00:00.000Z",
    nextCheckAt: "2026-03-29T17:00:00.000Z",
    createdAt: "2026-03-18T09:45:00.000Z",
    updatedAt: "2026-03-29T15:00:00.000Z",
    extensions: [
      {
        id: "ext-4",
        tld: ".de",
        fqdn: "acmesecure.de",
        status: "provider_error",
        lastCheckedAt: "2026-03-29T15:00:00.000Z",
        nextCheckAt: "2026-03-29T17:00:00.000Z",
        latencyMs: 3010,
        rawSummary: "Timeout bij upstream provider. Fallback ingepland.",
        sourceProvider: "denic-gateway",
        retryCount: 3,
        autoRegisterEnabled: false,
        notifyEnabled: true,
      },
      {
        id: "ext-5",
        tld: ".eu",
        fqdn: "acmesecure.eu",
        status: "registered",
        lastCheckedAt: "2026-03-29T15:00:00.000Z",
        nextCheckAt: "2026-03-29T17:00:00.000Z",
        latencyMs: 174,
        rawSummary: "EURid-register meldde een actieve registratie.",
        sourceProvider: "whois-generic",
        retryCount: 0,
        autoRegisterEnabled: false,
        notifyEnabled: true,
      },
      {
        id: "ext-6",
        tld: ".fr",
        fqdn: "acmesecure.fr",
        status: "unknown",
        lastCheckedAt: "2026-03-29T15:00:00.000Z",
        nextCheckAt: "2026-03-29T17:00:00.000Z",
        latencyMs: 888,
        rawSummary: "Dubbelzinnige registry-respons, gemarkeerd voor retry.",
        sourceProvider: "afnic-adapter",
        retryCount: 2,
        autoRegisterEnabled: false,
        notifyEnabled: true,
      },
    ],
  },
  {
    id: "dw-3",
    rootName: "merkpilot",
    displayName: "merkpilot e-commerce-monitor",
    state: "active",
    frequency: "daily",
    actionMode: "LOG_ONLY",
    priority: "low",
    tags: ["e-commerce", "archive"],
    notes: "Alleen logging; gebruikt voor trendanalyse.",
    owner: {
      id: "user-3",
      name: "Nina Vos",
      email: "nina@monitoring.internal",
      role: "OPERATOR",
      teamId: "team-2",
    },
    team: mockTeams[1],
    ntfyEnabled: false,
    autoRegisterEnabled: false,
    registrarLinked: false,
    lastCheckAt: "2026-03-29T00:01:00.000Z",
    nextCheckAt: "2026-03-30T00:01:00.000Z",
    createdAt: "2026-03-15T11:25:00.000Z",
    updatedAt: "2026-03-29T00:01:00.000Z",
    extensions: [
      {
        id: "ext-7",
        tld: ".net",
        fqdn: "merkpilot.net",
        status: "registered",
        lastCheckedAt: "2026-03-29T00:01:00.000Z",
        nextCheckAt: "2026-03-30T00:01:00.000Z",
        latencyMs: 143,
        rawSummary: "Registry-record aanwezig.",
        sourceProvider: "whois-generic",
        retryCount: 0,
        autoRegisterEnabled: false,
        notifyEnabled: false,
      },
      {
        id: "ext-8",
        tld: ".org",
        fqdn: "merkpilot.org",
        status: "registered",
        lastCheckedAt: "2026-03-29T00:01:00.000Z",
        nextCheckAt: "2026-03-30T00:01:00.000Z",
        latencyMs: 167,
        rawSummary: "Registry-record aanwezig.",
        sourceProvider: "whois-generic",
        retryCount: 0,
        autoRegisterEnabled: false,
        notifyEnabled: false,
      },
    ],
  },
  {
    id: "dw-4",
    rootName: "terraforge",
    displayName: "terraforge VK en Benelux",
    state: "paused",
    frequency: "custom",
    customSchedule: "*/20 8-18 * * 1-5",
    actionMode: "NOTIFY",
    priority: "high",
    tags: ["legal-hold", "uk"],
    notes: "Pauze wegens lopende juridische procedure.",
    owner: {
      id: "user-2",
      name: "Joris Meijer",
      email: "joris@monitoring.internal",
      role: "SECURITY_ANALYST",
      teamId: "team-1",
    },
    team: mockTeams[0],
    ntfyEnabled: true,
    ntfyTopic: "legal-escalations",
    autoRegisterEnabled: false,
    registrarLinked: true,
    lastCheckAt: "2026-03-28T16:20:00.000Z",
    nextCheckAt: "2026-03-29T08:00:00.000Z",
    createdAt: "2026-03-12T14:50:00.000Z",
    updatedAt: "2026-03-28T16:20:00.000Z",
    extensions: [
      {
        id: "ext-9",
        tld: ".co.uk",
        fqdn: "terraforge.co.uk",
        status: "registered",
        lastCheckedAt: "2026-03-28T16:20:00.000Z",
        nextCheckAt: "2026-03-29T08:00:00.000Z",
        latencyMs: 195,
        rawSummary: "Nominet geeft een bestaande registratie aan.",
        sourceProvider: "nominet-adapter",
        retryCount: 0,
        autoRegisterEnabled: false,
        notifyEnabled: true,
      },
      {
        id: "ext-10",
        tld: ".be",
        fqdn: "terraforge.be",
        status: "registered",
        lastCheckedAt: "2026-03-28T16:20:00.000Z",
        nextCheckAt: "2026-03-29T08:00:00.000Z",
        latencyMs: 166,
        rawSummary: "DNS Belgium-register geeft een toegewezen naam aan.",
        sourceProvider: "whois-generic",
        retryCount: 0,
        autoRegisterEnabled: false,
        notifyEnabled: true,
      },
    ],
  },
];

export const mockCheckRuns: CheckRun[] = [
  {
    id: "check-1",
    domainWatchId: "dw-1",
    fqdn: "northgrid.io",
    tld: ".io",
    result: "available",
    rawSummary: "Geen registry-match teruggekregen.",
    latencyMs: 221,
    sourceProvider: "whois-fallback",
    retryCount: 1,
    checkedAt: "2026-03-29T16:55:00.000Z",
  },
  {
    id: "check-2",
    domainWatchId: "dw-2",
    fqdn: "acmesecure.de",
    tld: ".de",
    result: "provider_error",
    rawSummary: "Timeout van denic-gateway.",
    latencyMs: 3010,
    sourceProvider: "denic-gateway",
    retryCount: 3,
    checkedAt: "2026-03-29T15:00:00.000Z",
  },
  {
    id: "check-3",
    domainWatchId: "dw-1",
    fqdn: "northgrid.nl",
    tld: ".nl",
    result: "registered",
    rawSummary: "SIDN-record gevonden.",
    latencyMs: 98,
    sourceProvider: "sidn-whois",
    retryCount: 0,
    checkedAt: "2026-03-29T16:55:00.000Z",
  },
];

export const mockRegistrationAttempts: RegistrationAttempt[] = [
  {
    id: "reg-1",
    domainWatchId: "dw-1",
    fqdn: "northgrid.io",
    provider: "openprovider-registrar",
    status: "pending",
    initiatedAt: "2026-03-29T16:56:00.000Z",
    metadataSummary: "Beschikbaarheidshercontrole in de wachtrij geplaatst vóór aankoop.",
    idempotencyKey: "idem-northgrid-io-202603291656",
  },
  {
    id: "reg-2",
    domainWatchId: "dw-4",
    fqdn: "terraforge.co.uk",
    provider: "openprovider-registrar",
    status: "failed",
    initiatedAt: "2026-03-26T09:14:00.000Z",
    completedAt: "2026-03-26T09:15:04.000Z",
    errorMessage: "Providerbeleid wees een niet-ondersteunde TLD af.",
    responseCode: "CF-422",
    metadataSummary: "Registratie geblokkeerd voordat kosten zijn gemaakt.",
    idempotencyKey: "idem-terraforge-couk-202603260914",
  },
];

export const mockNotificationEvents: NotificationEvent[] = [
  {
    id: "notif-1",
    domainWatchId: "dw-1",
    channel: "ntfy",
    target: "northgrid-domain-alerts",
    title: "Domein beschikbaar",
    message: "northgrid.io is beschikbaar. Auto-register is ingeschakeld.",
    status: "sent",
    createdAt: "2026-03-29T16:56:10.000Z",
    sentAt: "2026-03-29T16:56:12.000Z",
  },
  {
    id: "notif-2",
    domainWatchId: "dw-1",
    channel: "webhook",
    target: "https://hooks.internal.example/domain-events",
    title: "Auto-register in wachtrij",
    message: "Openprovider-registratiepoging voor northgrid.io is in de wachtrij geplaatst.",
    status: "queued",
    createdAt: "2026-03-29T16:56:13.000Z",
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: "audit-1",
    actor: "Eva van Rijn",
    actorRole: "ADMIN",
    action: "domain_watch.updated",
    entityType: "DomainWatch",
    entityId: "dw-1",
    summary: "Openprovider auto-register ingeschakeld voor de northgrid-sweep.",
    ipAddress: "203.0.113.10",
    userAgent: "Chrome 134 / macOS",
    severity: "info",
    timestamp: "2026-03-29T16:20:00.000Z",
    result: "success",
  },
  {
    id: "audit-2",
    actor: "Systeemworker",
    actorRole: "OPERATOR",
    action: "availability.detected",
    entityType: "DomainExtension",
    entityId: "ext-2",
    summary: "northgrid.io is naar BESCHIKBAAR verplaatst en de notificatiepipeline is gestart.",
    ipAddress: "10.0.0.22",
    userAgent: "bullmq/check-worker",
    severity: "critical",
    timestamp: "2026-03-29T16:55:05.000Z",
    result: "success",
  },
  {
    id: "audit-3",
    actor: "Joris Meijer",
    actorRole: "SECURITY_ANALYST",
    action: "domain_watch.paused",
    entityType: "DomainWatch",
    entityId: "dw-4",
    summary: "terraforge VK en Benelux is gepauzeerd wegens juridische hold.",
    ipAddress: "198.51.100.47",
    userAgent: "Firefox 137 / Windows",
    severity: "warning",
    timestamp: "2026-03-28T16:25:00.000Z",
    result: "success",
  },
  {
    id: "audit-4",
    actor: "Systeemworker",
    actorRole: "OPERATOR",
    action: "provider.error",
    entityType: "CheckRun",
    entityId: "check-2",
    summary: "De time-outdrempel van denic-gateway is bereikt voor acmesecure.de.",
    ipAddress: "10.0.0.22",
    userAgent: "bullmq/check-worker",
    severity: "critical",
    timestamp: "2026-03-29T15:00:20.000Z",
    result: "failed",
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  metrics: [
    { id: "metric-1", label: "Gemonitorde domeinen", value: "4", delta: "+1 deze week", trend: "up" },
    { id: "metric-2", label: "Beschikbaar in 24 uur", value: "1", delta: "northgrid.io", trend: "up" },
    { id: "metric-3", label: "Auto-registraties geslaagd", value: "12", delta: "+2 vs gisteren", trend: "up" },
    { id: "metric-4", label: "Fouten en retries", value: "7", delta: "2 providers vragen aandacht", trend: "down" },
  ],
  recentEvents: [
    {
      id: "event-1",
      title: "Beschikbaarheid gedetecteerd",
      detail: "northgrid.io werd beschikbaar en in de Openprovider-registratiequeue geplaatst.",
      timestamp: "2026-03-29T16:56:00.000Z",
      tone: "success",
    },
    {
      id: "event-2",
      title: "Providerdrempel bereikt",
      detail: "acmesecure.de bereikte drie retries tegen denic-gateway.",
      timestamp: "2026-03-29T15:00:20.000Z",
      tone: "warning",
    },
    {
      id: "event-3",
      title: "Juridische hold actief",
      detail: "De terraforge-monitor blijft gepauzeerd tot de review van 31 maart 2026.",
      timestamp: "2026-03-28T16:25:00.000Z",
      tone: "info",
    },
  ],
  recentAvailableDomains: mockDomainWatches[0].extensions.filter((extension) => extension.status === "available"),
  queue: {
    pending: 18,
    active: 3,
    delayed: 6,
    failed: 2,
  },
  systemHealth: [
    {
      id: "health-1",
      name: "API & Auth",
      status: "healthy",
      summary: "Nominale respons",
      detail: "Mediane latency 94 ms in het laatste uur.",
    },
    {
      id: "health-2",
      name: "WHOIS-providers",
      status: "degraded",
      summary: "1 provider onder druk",
      detail: "De timeout-ratio van denic-gateway ligt boven de drempel.",
    },
    {
      id: "health-3",
      name: "Registratiequeue",
      status: "healthy",
      summary: "Backlog onder controle",
      detail: "3 actieve jobs, geen groei in de dead-letter-queue.",
    },
  ],
  upcomingChecks: [
    {
      id: "next-1",
      fqdn: "northgrid.com",
      owner: "Eva van Rijn",
      nextRunAt: "2026-03-29T17:00:00.000Z",
      queue: "domain-checks",
    },
    {
      id: "next-2",
      fqdn: "acmesecure.de",
      owner: "Joris Meijer",
      nextRunAt: "2026-03-29T17:00:00.000Z",
      queue: "domain-checks",
    },
    {
      id: "next-3",
      fqdn: "northgrid.io",
      owner: "Eva van Rijn",
      nextRunAt: "2026-03-29T17:02:00.000Z",
      queue: "registration-attempts",
    },
  ],
  failuresByProvider: [
    { provider: "denic-gateway", failures: 3, retries: 6 },
    { provider: "whois-fallback", failures: 1, retries: 1 },
    { provider: "openprovider-registrar", failures: 1, retries: 2 },
  ],
};

export const mockSettings: AppSettings = {
  openprovider: {
    enabled: true,
    usernameConfigured: true,
    passwordConfigured: true,
    ownerHandle: "CP000000-NL",
    adminHandle: "CP000000-NL",
    techHandle: "CP000000-NL",
    billingHandle: "CP000000-NL",
    nsGroup: "op-default",
    defaultRegistrar: "Openprovider",
    testMode: true,
  },
  notifications: {
    ntfy: {
      enabled: true,
      serverUrl: "https://ntfy.sh",
      topic: "platform-domain-monitoring",
      authTokenConfigured: true,
      customHeadersConfigured: false,
    },
    emailEnabled: true,
    webhookEnabled: true,
    webhookUrl: "https://hooks.internal.example/domain-monitoring",
  },
  providerConfig: {
    whoisFallbackEnabled: true,
    genericWhoisEndpoint: "tcp://whois.verisign-grs.com:43",
    supportedProviders: ["sidn-whois", "whois-generic", "openprovider-registrar", "denic-gateway"],
    retentionDays: 180,
  },
  defaultIntervals: ["every_5_minutes", "every_15_minutes", "hourly", "daily"],
  roles: [
    {
      id: "role-1",
      key: "ADMIN",
      name: "Administrator",
      description: "Volledige toegang tot instellingen, audit en registraties.",
    },
    {
      id: "role-2",
      key: "SECURITY_ANALYST",
      name: "Security-analist",
      description: "Beheert domeinen, checks en escalaties zonder systeeminstellingen.",
    },
    {
      id: "role-3",
      key: "OPERATOR",
      name: "Operator",
      description: "Mag checks triggeren en status opvolgen.",
    },
    {
      id: "role-4",
      key: "VIEWER",
      name: "Lezer",
      description: "Alleen-lezenrechten voor monitoring en audit.",
    },
  ],
};
